// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'invoice_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$InvoiceImpl _$$InvoiceImplFromJson(Map<String, dynamic> json) =>
    _$InvoiceImpl(
      id: json['id'] as int,
      id_pelanggan: json['id_pelanggan'] as int,
      meteran_awal: json['meteran_awal'] as String,
      meteran_akhir: json['meteran_akhir'] as String,
      tgl_pencatatan: json['tgl_pencatatan'] as String,
      periode_tahun: json['periode_tahun'] as int,
      periode_bulan: json['periode_bulan'] as int,
      jumlah_pemakaian: json['jumlah_pemakaian'] as String,
      tagihan_pemakaian: json['tagihan_pemakaian'] as int,
      tagihan_administrasi: json['tagihan_administrasi'] as int,
      tagihan_beban: json['tagihan_beban'] as int,
      total_tagihan: json['total_tagihan'] as int,
      noref_tagihan: json['noref_tagihan'] as String,
      kode_billing: json['kode_billing'] as String?,
      denda_pemakaian: json['denda_pemakaian'] as int?,
      denda_administrasi: json['denda_administrasi'] as int?,
      total_denda: json['total_denda'] as int?,
      status_pembayaran: json['status_pembayaran'] as int,
      nomor: json['nomor'] as String,
      nama_pel: json['nama_pel'] as String,
      alamat_pel: json['alamat_pel'] as String,
      gol_tarif: json['gol_tarif'] as String,
      dusun: json['dusun'] as String,
      desa: json['desa'] as String,
      kec: json['kec'] as String,
      operator_pencatat: json['operator_pencatat'] as String,
      status_tagihan: json['status_tagihan'] as String,
      periode_bulan_name: json['periode_bulan_name'] as String?,
      pembayaran_id: json['pembayaran_id'] as int?,
      tgl_pembayaran: json['tgl_pembayaran'] as String?,
      channel_pembayaran: json['channel_pembayaran'] as String?,
      operator_pembayaran: json['operator_pembayaran'] as String?,
      pembayaran_tagihan_pemakaian:
          json['pembayaran_tagihan_pemakaian'] as int?,
      pembayaran_tagihan_administrasi:
          json['pembayaran_tagihan_administrasi'] as int?,
      pembayaran_tagihan_beban: json['pembayaran_tagihan_beban'] as int?,
      pembayaran_denda_pemakaian: json['pembayaran_denda_pemakaian'] as int?,
      pembayaran_denda_administrasi:
          json['pembayaran_denda_administrasi'] as int?,
      total_pembayaran: json['total_pembayaran'] as int?,
      noref_pembayaran: json['noref_pembayaran'] as String?,
      status_setoran: json['status_setoran'] as String?,
      struk: json['struk'] as String?,
    );

Map<String, dynamic> _$$InvoiceImplToJson(_$InvoiceImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'id_pelanggan': instance.id_pelanggan,
      'meteran_awal': instance.meteran_awal,
      'meteran_akhir': instance.meteran_akhir,
      'tgl_pencatatan': instance.tgl_pencatatan,
      'periode_tahun': instance.periode_tahun,
      'periode_bulan': instance.periode_bulan,
      'jumlah_pemakaian': instance.jumlah_pemakaian,
      'tagihan_pemakaian': instance.tagihan_pemakaian,
      'tagihan_administrasi': instance.tagihan_administrasi,
      'tagihan_beban': instance.tagihan_beban,
      'total_tagihan': instance.total_tagihan,
      'noref_tagihan': instance.noref_tagihan,
      'kode_billing': instance.kode_billing,
      'denda_pemakaian': instance.denda_pemakaian,
      'denda_administrasi': instance.denda_administrasi,
      'total_denda': instance.total_denda,
      'status_pembayaran': instance.status_pembayaran,
      'nomor': instance.nomor,
      'nama_pel': instance.nama_pel,
      'alamat_pel': instance.alamat_pel,
      'gol_tarif': instance.gol_tarif,
      'dusun': instance.dusun,
      'desa': instance.desa,
      'kec': instance.kec,
      'operator_pencatat': instance.operator_pencatat,
      'status_tagihan': instance.status_tagihan,
      'periode_bulan_name': instance.periode_bulan_name,
      'pembayaran_id': instance.pembayaran_id,
      'tgl_pembayaran': instance.tgl_pembayaran,
      'channel_pembayaran': instance.channel_pembayaran,
      'operator_pembayaran': instance.operator_pembayaran,
      'pembayaran_tagihan_pemakaian': instance.pembayaran_tagihan_pemakaian,
      'pembayaran_tagihan_administrasi':
          instance.pembayaran_tagihan_administrasi,
      'pembayaran_tagihan_beban': instance.pembayaran_tagihan_beban,
      'pembayaran_denda_pemakaian': instance.pembayaran_denda_pemakaian,
      'pembayaran_denda_administrasi': instance.pembayaran_denda_administrasi,
      'total_pembayaran': instance.total_pembayaran,
      'noref_pembayaran': instance.noref_pembayaran,
      'status_setoran': instance.status_setoran,
      'struk': instance.struk,
    };
